### ISSUE TITLE
random error with mthread on py27

### ISSUE THREAD

**Issue by reverbc** [reverbc/pytest-concurrent#6] opened 2017-08-10 05:25 UTC
Sometimes the multi-thread mode on py27 will receive errors as below example: https://travis-ci.org/reverbc/pytest-concurrent/jobs/262948622

Need to take a deeper look to find the cause.

**Comment by jamesw96** [comment] 2017-08-11 00:46
I was unable to reproduce this error, I will close this issue for now. 
Let me know if you see this error appear again!

**Closed by jamesw96** 2017-08-11 00:46 UTC
Labels: bug
